Repository FRONTENDBOOTCAMP-14th/ui-project-team-7, pull requests merged in 2025-05, with the labels that each got.

#3 docs: 컨벤션 관련 추가 작성
  README.md
Labels: documentation, initialize

#12 docs: CSS 속성 정렬 순서 카테고리 수정
  README.md
Labels: documentation

#11 feat: 버튼 구현
  src/components/btn/index.html
  src/components/btn/style.css
  src/components/sub-btn/index.html
  src/components/sub-btn/style.css
Labels: feature

#10 feat : 헤더 구현
  src/assets/profile/profile.avif
  src/assets/profile/profile.jpg
  src/assets/profile/profile.webp
  src/components/header-home/index.html
  src/components/header-home/style.css
  src/components/header/index.html
  src/components/header/style.css
Labels: feature

#13 feat: comment 컴포넌트 구현
  src/components/btn/style.css
  src/components/comment/index.html
  src/components/comment/style.css
Labels: feature
