Repository FRONTENDBOOTCAMP-14th/ui-project-team-7, pull requests merged in 2025-06, with the labels that each got.

#20 feat: bookcard 컴포넌트 구현
  src/assets/bookcover-img/Background.avif
  src/assets/bookcover-img/Background.jpg
  src/assets/bookcover-img/Background.webp
  src/components/bookcover/index.html
  src/components/bookcover/style.css
Labels: feature

#23 feat: auth 페이지 관련 input, button들 구현
  src/components/auth/auth-button.css
  src/components/auth/auth-input-signup.css
  src/components/auth/auth-input.css
  src/components/auth/index.html
  src/components/auth/style.css
Labels: feature

#22 Feat: profile 구현
  src/components/profile/index.html
  src/components/profile/style.css
Labels: feature

#33 Feat/components
  index.html
  src/assets/bookcover-img/Background.avif
  src/assets/bookcover-img/Background.jpg
  src/assets/bookcover-img/Background.webp
  src/assets/profile/profile.avif
  src/assets/profile/profile.jpg
  src/assets/profile/profile.webp
  src/components/auth/auth-button.css
  src/components/auth/auth-input-signup.css
  src/components/auth/auth-input.css
  src/components/auth/index.html
  src/components/auth/style.css
  src/components/avatar/index.html
  src/components/avatar/style.css
  src/components/bookcover/index.html
  src/components/bookcover/style.css
  src/components/btn/index.html
  src/components/btn/style.css
  src/components/comment/index.html
  src/components/comment/style.css
  src/components/header-home/index.html
  src/components/header-home/style.css
  src/components/header/index.html
  src/components/header/style.css
  src/components/navigation/index.html
  src/components/navigation/style.css
  src/components/profile/index.html
  src/components/profile/style.css
  src/components/sub-btn/index.html
  src/components/sub-btn/style.css
  src/reset.css
Labels: feature

#36 Fix/components error
  src/assets/bookcover-img/background1.avif
  src/assets/bookcover-img/background1.jpg
  src/assets/bookcover-img/background1.webp
  src/components/auth/auth-input-signup.css
  src/components/bookcover/index.html
  src/components/btn/index.html
  src/components/navigation/index.html
  src/components/profile/style.css
  src/components/sub-btn/index.html
  src/reset.css
Labels: bug

#46 feat/pages home 페이지 구현
  src/assets/icon/facebook.svg
  src/assets/icon/kakao.svg
  src/assets/icon/twitter.svg
  src/pages/home/home.js
  src/pages/home/index.html
  src/pages/home/style.css
Labels: feature

#44 feat: onboarding 페이지 구현
  src/pages/onboarding/index.html
  src/pages/onboarding/style.css
Labels: feature

#43 feat: 내 서랍 페이지 구현
  src/assets/mine/right-arrow.svg
  src/pages/mine/index.html
  src/pages/mine/style.css
Labels: feature

#32 feat : post-detail 상세페이지 구현
  src/assets/post-detail/heart.avif
  src/assets/post-detail/heart.jpg
  src/assets/post-detail/heart.webp
  src/assets/post-detail/parking.avif
  src/assets/post-detail/parking.jpg
  src/assets/post-detail/parking.webp
  src/assets/profile/profile2.avif
  src/assets/profile/profile2.jpg
  src/assets/profile/profile2.webp
  src/assets/profile/profile3.avif
  src/assets/profile/profile3.jpg
  src/assets/profile/profile3.webp
  src/assets/profile/profile4.avif
  src/assets/profile/profile4.jpg
  src/assets/profile/profile4.webp
  src/components/comment/style.css
  src/components/sub-btn/index.html
  src/components/sub-btn/style.css
  src/pages/post/detail/index.html
  src/pages/post/detail/style.css
Labels: feature

#31 feat: 글쓰기 페이지 구현
  src/assets/icon/keyboard-on.svg
  src/assets/icon/picture.svg
  src/pages/post/upload/index.html
  src/pages/post/upload/style.css
Labels: feature

#47 feat: 네비게이션 컴포넌트 추가
  src/pages/home/index.html
  src/pages/home/style.css
Labels: refactor
